project_id = "tdvuohfextmqhqsjiixa"

[functions.setup-owner]
verify_jwt = false

[functions.create-staff]
verify_jwt = false

[functions.delete-staff]
verify_jwt = false

[functions.update-staff]
verify_jwt = false
